FROM httpd:latest

# Copy your custom SSL/proxy config (apache.conf) into conf/extra/httpd-ssl.conf
COPY apache.conf /usr/local/apache2/conf/extra/httpd-ssl.conf

# Enable all needed modules in httpd.conf
RUN sed -i 's/^#LoadModule ssl_module/LoadModule ssl_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#LoadModule socache_shmcb_module/LoadModule socache_shmcb_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#LoadModule proxy_module/LoadModule proxy_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#LoadModule proxy_http_module/LoadModule proxy_http_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#LoadModule proxy_ssl_module/LoadModule proxy_ssl_module/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#Include conf\/extra\/httpd-ssl.conf/Include conf\/extra\/httpd-ssl.conf/' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/^#LoadModule rewrite_module/LoadModule rewrite_module/' \
    /usr/local/apache2/conf/httpd.conf


# Expose both HTTP and HTTPS
EXPOSE 443
